### list users

GET http://localhost:3000/user

### Create a new User
POST http://localhost:3000/user/register
content-type: application/json

{
    "name": "tres",
    "username": "tre3",
    "email": "tre@gmail.com",
    "password": "tre3"
}

### Get particular user
GET http://localhost:3000/user/1

### SignIn
POST http://localhost:3000/user/login
content-type:  application/json

{
    "email": "maridius98@gmail.com",
    "password": "zelenasalata1"
}

### Get currrently signed in user
GET http://localhost:3000/user/whoami

### Get user by link
GET http://localhost:3000/user/MaridiuS

### Logout current user
POST http://localhost:3000/user/logout

