### list users

GET http://localhost:3000/user

### Create a new User
POST http://localhost:3000/user/register
content-type: application/json

{
    "name": "Milos",
    "lastName": "Miljkovic",
    "email": "maridiu@gmail.com",
    "password": "secretPassword"
}

### Get particular user
GET http://localhost:3000/user/1

### SignIn
POST http://localhost:3000/user/login
content-type:  application/json

{
    "email": "maridiu@gmail.com",
    "password": "secretPassword"
}

### Get currrenlty singed in user
GET http://localhost:3000/user/whoami

### Get user by ID
GET http://localhost:3000/user/6461095d9563f01d797f6bca